### ISSUE TITLE
Issue - multiple devices fail?

### ISSUE THREAD

**Issue by csmarshall** [plainsane/homebridge-unifi-kids-cry#6]
I *assumed* that since "devices" is an array I could do:
```
            "devices": [
                {
                    "name": "Charles - iPhone",
                    "mac": "00:00:00:00:00:01"
                },
                {
                    "name": "Chloe - iPad",
                    "mac": "00:00:00:00:00:02"
                }
            ],
```
But sadly it looks to error: 
```
Jul  2 06:29:38 pecan hoobs[299]: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7257520b-1c86-498f-a23c-edc9309359e8
Jul  2 06:29:38 pecan hoobs[299]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:286:27)
Jul  2 06:29:38 pecan hoobs[299]:     at Server.configCachedPlatformAccessories (/usr/lib/node_modules/@hoobs/hoobs/bridge/server.js:348:25)
Jul  2 06:29:38 pecan hoobs[299]:     at Server.run (/usr/lib/node_modules/@hoobs/hoobs/bridge/server.js:94:14)
Jul  2 06:29:38 pecan hoobs[299]:     at module.exports (/usr/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
Jul  2 06:29:38 pecan hoobs[299]:     at Object.<anonymous> (/usr/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
Jul  2 06:29:38 pecan hoobs[299]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jul  2 06:29:38 pecan hoobs[299]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Jul  2 06:29:38 pecan hoobs[299]:     at Module.load (internal/modules/cjs/loader.js:986:32)
Jul  2 06:29:38 pecan hoobs[299]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
Jul  2 06:29:38 pecan hoobs[299]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Jul  2 06:29:38 pecan hoobs[299]:     at internal/main/run_main_module.js:17:47
```
What am I missing?

**Comment by csmarshall** [comment]
Odd, I think it's because of the accessory cache being hooked to the device.  I'm sure there's a quicker way, but I:
1. Copied out my config stanza
2. Uninstalled the plugin, and restarted homebridge
3. Re-installed the plugin, and restarted, homebridge,
4. Re-added the original stanza, and *again* restarted homebridge
5. Profit

I was even able to add another device without complication.
